apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: s-kaupat-scraper
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        # Allow up to 60 seconds for startup
        run.googleapis.com/timeout: "300s"
        # CPU allocation during request processing only
        run.googleapis.com/cpu-throttling: "true"
        # Min/max instances
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        # Execution environment
        run.googleapis.com/execution-environment: gen2
    spec:
      # Service account for BigQuery access
      serviceAccountName: s-kaupat-scraper@ruokahinta-scraper-1748695687.iam.gserviceaccount.com
      containerConcurrency: 10
      containers:
      - name: s-kaupat-scraper
        image: gcr.io/ruokahinta-scraper-1748695687/s-kaupat-scraper:latest
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "ruokahinta-scraper-1748695687"
        - name: BIGQUERY_DATASET_ID
          value: "s_kaupat"
        - name: BIGQUERY_TABLE_ID
          value: "stores"
        - name: BIGQUERY_LOCATION
          value: "europe-north1"
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        # Health check
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 60
