[tool.poetry]
name = "s-kaupat-scraper"
version = "0.1.0"
description = "Scrape s-kaupat.fi → BigQuery"
authors = ["Harri Juntunen <harri@juntunen.ai>"]
readme = "README.md"
packages = [{include = "scraper"}, {include = "loader"}]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
black = "^23.0.0"
mypy = "^1.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
