steps:
  # Build the Docker image from root directory
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}:latest'
      - '-f'
      - 'recipe_ai/Dockerfile'
      - '.'
    env:
      - 'PROJECT_ID=${_PROJECT_ID}'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}:latest'

# Substitutions for the build
substitutions:
  _SERVICE_NAME: 'ai-recipe-generator'
  _PROJECT_ID: '${PROJECT_ID}'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'

# Build timeout (AI models can take time to build)
timeout: '1200s'

# Image to be built
images:
  - 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}:latest'
