apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ai-recipe-generator
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        # Allow up to 5 minutes for startup (AI model loading)
        run.googleapis.com/timeout: "300s"
        # CPU allocation during request processing only
        run.googleapis.com/cpu-throttling: "false"
        # Min/max instances
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
        # Execution environment
        run.googleapis.com/execution-environment: gen2
    spec:
      # Service account for Vertex AI and BigQuery access
      serviceAccountName: recipe-ai-service@${PROJECT_ID}.iam.gserviceaccount.com
      containerConcurrency: 5
      containers:
      - name: ai-recipe-generator
        image: gcr.io/${PROJECT_ID}/ai-recipe-generator:latest
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "${PROJECT_ID}"
        - name: VERTEX_AI_LOCATION
          value: "us-central1"
        - name: VERTEX_AI_MODEL
          value: "gemini-2.0-flash-001"
        - name: BIGQUERY_DATASET_ID
          value: "scraped_data"
        - name: BIGQUERY_TABLE_ID
          value: "products"
        - name: BIGQUERY_LOCATION
          value: "europe-north1"
        - name: STREAMLIT_SERVER_PORT
          value: "8080"
        - name: STREAMLIT_SERVER_ADDRESS
          value: "0.0.0.0"
        - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
          value: "false"
        - name: STREAMLIT_SERVER_HEADLESS
          value: "true"
        resources:
          limits:
            cpu: "4"
            memory: "4Gi"
          requests:
            cpu: "2"
            memory: "2Gi"
        # Health check
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
